# Generated by Django 6.1.1 on 2026-10-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_employee_gender_employee_image_employee_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='inactive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
